version: '3.7'

services:
  web:
    build: .
    command: gunicorn -w 4 realty.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/home/app/web
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8080:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data:
  static_volume: