# Generated by Django 3.0.4 on 2020-07-03 20:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusesRealty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('url', models.SlugField(max_length=250, unique=True)),
                ('overview', models.CharField(max_length=255, verbose_name='Overview')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_data', models.TextField(verbose_name='Description data')),
                ('description_details', models.TextField(verbose_name='Detailed description')),
                ('place', models.CharField(max_length=255, verbose_name='Object location')),
                ('google_map_data', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Data location')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('area', models.IntegerField(verbose_name='Area')),
                ('floor_number', models.IntegerField(verbose_name='Floor number')),
                ('namber_of_floors', models.IntegerField(verbose_name='Namber of floors')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('buiding', models.IntegerField(verbose_name='Buiding')),
                ('adaptation', models.IntegerField(verbose_name='Adaptation')),
                ('rooms', models.IntegerField(verbose_name='Rooms')),
                ('garage', models.BooleanField(verbose_name='Garage')),
                ('pool', models.BooleanField(verbose_name='Pool')),
                ('furniture', models.BooleanField(verbose_name='Furniture')),
                ('air_conditioner', models.BooleanField(verbose_name='Air conditioner')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delited', models.DateTimeField(auto_now=True)),
                ('published', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('status_realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.StatusesRealty', verbose_name='Status realty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'object',
                'verbose_name_plural': 'objects',
            },
        ),
    ]
