# Generated by Django 3.0.4 on 2020-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='google_map_data',
        ),
        migrations.AddField(
            model_name='realty',
            name='lat',
            field=models.FloatField(default=1, max_length=50, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realty',
            name='long',
            field=models.FloatField(default=1, max_length=50, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
