# Generated by Django 3.0.4 on 2020-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200703_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='place',
            field=models.TextField(verbose_name='Object location'),
        ),
    ]
