# Generated by Django 3.0.4 on 2020-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200704_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
