# Generated by Django 3.0.4 on 2020-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='add_images',
        ),
        migrations.AddField(
            model_name='realty',
            name='add_images',
            field=models.ManyToManyField(to='catalog.Images'),
        ),
    ]
