# Generated by Django 3.0.4 on 2020-07-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200704_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='add_images',
        ),
        migrations.AddField(
            model_name='realty',
            name='add_images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Images'),
            preserve_default=False,
        ),
    ]
