# Generated by Django 3.0.4 on 2020-07-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200704_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realty',
            name='add_images',
        ),
        migrations.AddField(
            model_name='images',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Realty', verbose_name='Photos'),
        ),
    ]
